
/*  Test Script */
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, 
Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated) 
values (1,'Single','Medium','','விண்மீன்கள்','பறவைகள்','ஊர்வன','தாவரங்கள்','2','1.0',2);
/*  Test Script */

insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','கடவுள் ஐந்தாம் நாளில் எவற்றை உருவாக்கினார்?','விண்மீன்கள்','பறவைகள்','ஊர்வன','தாவரங்கள்','2','1.0',2);

insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','கணவன் தன் தாய் தந்தையைவிட்டு மனைவியுடன் ஒன்றித்திருப்பான் . ஏன்?','இருவரும் ஒரே உடலாய் இருப்பதால்','சதையின் சதையாய் ஆனதால்','விலா எலும்பில் இருந்து எடுக்கப்பட்டதால்','திருமணம் ஆனதால்','1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','நீ ஏன் சினமுற்றிருக்கிறாய்?இது யாருடைய கூற்று?','காயீன்','ஆபேல்','ஆண்டவர்','ஆபிரகாம்','3','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium',' ஆதாம் எத்தனை வருஷம் வாழ்ந்தான்?','930','912','950','927','1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','மண்ணுலகில் மனிதரை உருவாக்கியதற்காக ஆண்டவர் ஏன் மனம் வருந்தினார்?','மனித இதயத்தின் சிந்தனை முழுதும் தீமையே','கடவுளுக்கு கீழ்படியாததால்','ஆண்டவரை மறந்ததால்','பாவம்','1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','நோவாவின் காலத்தில் எத்தனை நாள் மண்ணுலகில் வெள்ளம் பாய்ந்து பெருகிற்று?','40 நாள்','150 நாள்','15 நாள்','42 நாள்','2','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium',' முதல் உடன்படிக்கையின் அடையாளமாக ஆண்டவர் எதை கொடுத்தார்?','விருத்தசேதனம்','மேகம்','வானவில்','நெருப்பு','3','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','ஆண்டவரே! எனக்கு என்ன தருவீர்?என ஆபிராம் ஏங்கியது எதற்காக?','குழந்தைக்காக','ஆசீருக்காக','உரிமைக்காக','நிலத்துக்காக','1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium',' தந்தை இறப்பதற்கு முன்னே இறந்த மகன் யார்?','தெராகு','நாகோர்','ஆரான்','ஆபிரகாம்','3','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','நீ என் சகோதரி எனச்சொல்லிவிடு, என்ற வரியை எங்கெங்கு வாசிக்கிறோம்?','12,20','12,18','19,20','22,23','1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','உன்னத கடவுளின் அர்ச்சராக இருந்தவர் பெயர் என்ன?','மெல்கிசேதேக்கு','சோதோம் ராஜா','சாலேம் ராஜா','காயீன்','1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','என்னை காண்பவரை நானும் இங்கே கண்டேன் அல்லவா? இது யாருடைய கூற்று?','இஸ்மயேல்','சாரா','ஆகார்','ஆபிரகாம்','3','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','ஒரே நாளில் தகப்பனுக்கும் மகனுக்கும் விருத்தசேதனம் செய்யப்பட்டது யார் யாருக்கு?','ஆபிரகாம்,இஸ்மயேல்','ஆபிரகாம்,ஈசாக்கு','லோத்து,ஈசாக்கு','ஈசாக்கு, இஸ்மயேல்','1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','சோதோம்,கொமோரா நகர்களின்மேல் ஆண்டவர் எதை வானத்திலிருந்து பொழியச்செய்தார்?','மழையும்,பனியும்','கந்தகமும்,நெருப்பும்','நெருப்பும்,இடி,மின்னல்','மழையும், நெருப்பும்','2','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','இதோ, உன் சகோதரருக்கு 1000 வெள்ளிக்காசு கொடுத்துள்ளேன். யார் யாருக்கு கொடுத்தது?','அபிமெலேக்கு சாராவிடம்','ஆபிரகாம் அபிமேலேக்கிடம்','கடவுள் ஆபிரகாமுக்கு','ஆபிரகாம் சாராவிடம்','1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','சாராய் ஆகாரை அழைத்து, அவளைத் தன் புருஷனாகிய ஆபிராமுக்கு மறுமனையாட்டியாகக் கொடுத்தாள்.','சரி','தவறு',null,null,'1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','என்னைக் காண்கிற தேவன் என்று பேரிட்டது சாராய்','சரி','தவறு',null,null,'2','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','ஆகார் ஆபிராமுக்கு இஸ்மவேலைப் பெற்றபோது, ஆபிராம் எண்பத்தாறு வயதாயிருந்தான்.','சரி','தவறு',null,null,'1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium',' நீர் வாழும் ஜந்துக்களை தேவன் எந்த நாளில் எண்டாக்கினார்','5ம் நாள்','4ம் நாள்','3 ஆம் நாள்','6ம் நாள்','1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','கர்த்தர் மேற்கே ஏதேன் என்னும் ஒரு தோட்டத்தை உண்டாக்கினார்','சரி','தவறு',null,null,'2','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','தோட்டத்துக்குத் தண்ணீர் பாயும்படி ஏதேனிலிருந்து ஒரு நதி ஓடி, அங்கேயிருந்து பிரிந்து ஐந்து பெரிய ஆறுகளாயிற்று.','சரி','தவறு',null,null,'2','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','ஆதாமின் மூத்த மகன் காயீன்','சரி','தவறு',null,null,'1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','ஈராத் மெகுயவேலைப் பெற்றான்','சரி','தவறு',null,null,'1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','பேழையின் நீளம் இருநூறு முழம்','சரி','தவறு',null,null,'2','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','ஜலப்பிரளயம் பூமியின்மேல் உண்டானபோது, நோவா அறுநூறு வயதாயிருந்தான்.','சரி','தவறு',null,null,'1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','மூடப்பட்ட மலைகளுக்கு மேலாய்ப் பதினைந்துமுழ உயரத்திற்கு ஜலம் பெருகிற்று.','சரி','தவறு',null,null,'1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','ஜலம் பூமியின்மேல் நூற்றென்பது நாள் மிகவும் பிரவாகித்துக்கொண்டிருந்தது.','சரி','தவறு',null,null,'2','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','காம் கானானுக்குத் தகப்பன்.','சரி','தவறு',null,null,'1','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','பிறக்கும் ஆண்பிள்ளைகளெல்லாம் ஏழாம் நாளிலே விருத்தசேதனம்பண்ணப்படவேண்டும்; ','சரி','தவறு',null,null,'2','1.0',2);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (1,'Single','Medium','இஸ்மவேல் எத்தனை பிரபுக்களைப் பெறுவான்; என்று கர்த்தர் சொன்னார்','10','12','11','15','2','1.0',2);


/* English*/
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','What is the age of Jesus when He died?','32','42',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','First chapter in Old Testament','Gensis','John','Matthew','Mark','1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','Do you love God','Yes','No',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','What is the meaning of Ebenezer','Youthful','Powerful','Helpful',null,'3','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','Do you like God.','No','Yes',null,null,'2','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','First book in New Testament','Matthew','Revelations',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','How Powerful is God.','Very powerful','less Powerful',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','Jesus Never Faile','Yes','No',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','Who is the light/Saviour','God','Solomon',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','Mother Of Jesus','Marry','Marthal',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','What is the age of Jesus when He died?','32','42',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','First chapter in Old Testament','Gensis','John','Matthew','Mark','1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','Do you love God','Yes','No',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','What is the meaning of Ebenezer','Youthful','Powerful','Helpful',null,'3','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','Do you like God.','No','Yes',null,null,'2','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','First book in New Testament','Matthew','Revelations',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','How Powerful is God.','Very powerful','less Powerful',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','Jesus Never Faile','Yes','No',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','Who is the light/Saviour','God','Solomon',null,null,'1','1.0',0);
insert into `QuizApplication_Dev`.`Questions`(SubGroupId, QuestionType, QuestionComplexity,QuestionDescr, Option1Descr,Option2Descr,Option3Descr,Option4Descr,AnswerOptionNbrs,MarksAllocated,QuestionLanguageNbr) values (10,'Single','Medium','Mother Of Jesus','Marry','Marthal',null,null,'1','1.0',0);
